apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: d-redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
  - name: redisweb
    protocol: TCP
    port: 7379
